package outbox

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	_ "github.com/mattn/go-sqlite3"

	"picoman/internal/tg"
)

const (
	maxMessageBytes = 4000
	maxAttempts     = 5
	baseBackoff     = time.Second
	maxBackoff      = time.Minute
)

type Store struct {
	db   *sql.DB
	bot  *tg.Client
	done chan struct{} // closed when Run exits

	// alert is a direct-to-user sink for internal outbox issues that we don't
	// want to route back through the outbox itself (offset persistence
	// failures, oversize messages, etc.). Set by daemon at startup.
	alert       func(text string)
	trimAlerted sync.Once
	persistAlerted sync.Once
}

type message struct {
	id        int64
	chatID    int64
	replyToID int64
	format    string
	text      string
	attempts  int
}

func Open(path string, bot *tg.Client) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite3", path)
	if err != nil {
		return nil, err
	}
	s := &Store{db: db, bot: bot, done: make(chan struct{})}
	if err := s.init(); err != nil {
		db.Close()
		return nil, err
	}
	_ = os.Chmod(path, 0o600)
	return s, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

func (s *Store) Enqueue(chatID int64, text string) error {
	return s.enqueue(chatID, 0, "", text)
}

func (s *Store) EnqueueReply(chatID, replyToID int64, text string) error {
	return s.enqueue(chatID, replyToID, "", text)
}

func (s *Store) EnqueueHTML(chatID int64, text string) error {
	return s.enqueue(chatID, 0, "html", text)
}

func (s *Store) EnqueueHTMLReply(chatID, replyToID int64, text string) error {
	return s.enqueue(chatID, replyToID, "html", text)
}

func (s *Store) enqueue(chatID, replyToID int64, format, text string) error {
	// Messages are generated by callers with bounded fields; if a producer
	// ever exceeds the Telegram limit we trim hard and keep going rather
	// than reassemble HTML across chunks (which loses tags and is fragile).
	if len(text) > maxMessageBytes {
		log.Printf("outbox message too long (chat=%d format=%q bytes=%d); hard-trimming", chatID, format, len(text))
		s.trimAlerted.Do(func() {
			s.fireAlert(fmt.Sprintf("⚠️ outbox hard-trim: message %d bytes (limit %d); producer bug", len(text), maxMessageBytes))
		})
		text = trimUTF8(text, maxMessageBytes)
	}
	return s.insert(replyToID, chatID, format, text)
}

// trimUTF8 cuts at most n bytes from s on a UTF-8 boundary.
func trimUTF8(s string, n int) string {
	if len(s) <= n {
		return s
	}
	for n > 0 && !utf8.RuneStart(s[n]) {
		n--
	}
	return s[:n]
}

func (s *Store) insert(replyToID, chatID int64, format, text string) error {
	_, err := s.db.Exec(`
insert into outbox(chat_id, reply_to_id, format, text, created_at)
values(?, ?, ?, ?, unixepoch())
`, chatID, replyToID, format, text)
	return err
}

// Done is closed when the Run goroutine has exited. Use it to wait before
// calling Flush during shutdown so two senders don't pick the same row.
func (s *Store) Done() <-chan struct{} { return s.done }

// SetAlertSink wires a direct-to-user notification function for internal
// issues. The sink should bypass this outbox so a broken outbox can still
// alert. May be nil (alerts then drop to the journal only).
func (s *Store) SetAlertSink(fn func(text string)) { s.alert = fn }

// fireAlert calls the alert sink if set, otherwise just logs.
func (s *Store) fireAlert(text string) {
	log.Printf("outbox alert: %s", text)
	if s.alert != nil {
		s.alert(text)
	}
}

func (s *Store) Run(ctx context.Context) {
	defer close(s.done)
	wait := baseBackoff
	for {
		err := s.SendOne(ctx)
		switch {
		case errors.Is(err, sql.ErrNoRows):
			wait = baseBackoff
			if !sleepCtx(ctx, time.Second) {
				return
			}
		case err == nil:
			wait = baseBackoff
		default:
			if !sleepCtx(ctx, wait) {
				return
			}
			wait *= 2
			if wait > maxBackoff {
				wait = maxBackoff
			}
		}
	}
}

func (s *Store) Flush(ctx context.Context) {
	for ctx.Err() == nil {
		err := s.SendOne(ctx)
		if errors.Is(err, sql.ErrNoRows) {
			return
		}
		if err != nil && !sleepCtx(ctx, time.Second) {
			return
		}
	}
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-t.C:
		return true
	case <-ctx.Done():
		return false
	}
}

func (s *Store) SendOne(ctx context.Context) error {
	msg, err := s.next()
	if err != nil {
		return err
	}
	sendErr := s.send(ctx, msg)
	if sendErr == nil {
		log.Printf("outbox sent id=%d chat=%d", msg.id, msg.chatID)
		return s.markSent(msg.id)
	}

	// Reply target gone: drop reply_to and retry on next tick.
	if msg.replyToID > 0 && isReplyTargetGone(sendErr) {
		log.Printf("outbox reply target gone id=%d chat=%d: %v", msg.id, msg.chatID, sendErr)
		_ = s.clearReplyTo(msg.id)
		return sendErr
	}

	// HTML rejected permanently (e.g. parse_error from a malformed tag in our
	// own generator): retry once as plain so users see *something* — visible
	// raw tags beat a dead-lettered message.
	if msg.format == "html" && isPermanent(sendErr) {
		plain := msg
		plain.format = ""
		if plainErr := s.send(ctx, plain); plainErr == nil {
			log.Printf("outbox sent (html→plain fallback) id=%d chat=%d: original %v", msg.id, msg.chatID, sendErr)
			_ = s.clearFormat(msg.id)
			return s.markSent(msg.id)
		} else {
			// Plain also rejected — fall through with the new error.
			sendErr = plainErr
		}
	}

	if !isPermanent(sendErr) {
		s.recordError(msg.id, sendErr)
		log.Printf("outbox transient id=%d chat=%d: %v", msg.id, msg.chatID, sendErr)
		// Honor Telegram's retry_after hint: if we keep hammering through it,
		// the API may escalate the cooldown. Cap at 5 min for safety.
		var apiErr *tg.APIError
		if errors.As(sendErr, &apiErr) && apiErr.RetryAfter > 0 {
			wait := time.Duration(apiErr.RetryAfter) * time.Second
			if wait > 5*time.Minute {
				wait = 5 * time.Minute
			}
			log.Printf("outbox honoring retry_after id=%d chat=%d wait=%s", msg.id, msg.chatID, wait)
			_ = sleepCtx(ctx, wait)
		}
		return sendErr
	}

	attempts := msg.attempts + 1
	s.fail(msg.id, attempts, sendErr)
	if attempts >= maxAttempts {
		s.markDead(msg.id)
		log.Printf("outbox dead id=%d chat=%d attempts=%d: %v", msg.id, msg.chatID, attempts, sendErr)
		go s.notifyDead(msg, sendErr)
		return nil
	}
	log.Printf("outbox permanent id=%d chat=%d attempts=%d: %v", msg.id, msg.chatID, attempts, sendErr)
	return sendErr
}

func isPermanent(err error) bool {
	var apiErr *tg.APIError
	return errors.As(err, &apiErr) && !apiErr.IsRetryable()
}

func (s *Store) send(ctx context.Context, msg message) error {
	switch {
	case msg.format == "html" && msg.replyToID > 0:
		return s.bot.SendHTMLReply(ctx, msg.chatID, msg.replyToID, msg.text)
	case msg.format == "html":
		return s.bot.SendHTML(ctx, msg.chatID, msg.text)
	case msg.replyToID > 0:
		return s.bot.SendReply(ctx, msg.chatID, msg.replyToID, msg.text)
	default:
		return s.bot.SendMessage(ctx, msg.chatID, msg.text)
	}
}

func isReplyTargetGone(err error) bool {
	var apiErr *tg.APIError
	if !errors.As(err, &apiErr) {
		return false
	}
	desc := strings.ToLower(apiErr.Description)
	if strings.Contains(desc, "message to be replied") {
		return true
	}
	return strings.Contains(desc, "reply") &&
		(strings.Contains(desc, "not found") ||
			strings.Contains(desc, "invalid") ||
			strings.Contains(desc, "deleted"))
}

func (s *Store) notifyDead(msg message, sendErr error) {
	text := fmt.Sprintf("outbox dead id=%d: %s", msg.id, sendErr)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_ = s.bot.SendMessage(ctx, msg.chatID, text)
}

func (s *Store) init() error {
	// Pragmas: WAL gives concurrent readers + one writer without "database is
	// locked" thrash; busy_timeout retries lock acquisition briefly instead of
	// failing immediately under contention.
	if _, err := s.db.Exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;`); err != nil {
		return err
	}
	_, err := s.db.Exec(`
create table if not exists outbox (
	id integer primary key autoincrement,
	chat_id integer not null,
	reply_to_id integer not null default 0,
	format text not null default '',
	text text not null,
	created_at integer not null,
	sent_at integer,
	dead_at integer,
	attempts integer not null default 0,
	last_error text not null default ''
);
create index if not exists outbox_pending on outbox(sent_at, dead_at, id);
create table if not exists kv (
	k text primary key,
	v text not null
);
`)
	return err
}

func (s *Store) next() (message, error) {
	var msg message
	err := s.db.QueryRow(`
select id, chat_id, reply_to_id, format, text, attempts
from outbox
where sent_at is null and dead_at is null
order by id
limit 1
`).Scan(&msg.id, &msg.chatID, &msg.replyToID, &msg.format, &msg.text, &msg.attempts)
	return msg, err
}

func (s *Store) markSent(id int64) error {
	_, err := s.db.Exec(`update outbox set sent_at = unixepoch() where id = ?`, id)
	return err
}

func (s *Store) markDead(id int64) {
	_, _ = s.db.Exec(`update outbox set dead_at = unixepoch() where id = ?`, id)
}

func (s *Store) clearReplyTo(id int64) error {
	_, err := s.db.Exec(`update outbox set reply_to_id = 0 where id = ?`, id)
	return err
}

func (s *Store) clearFormat(id int64) error {
	_, err := s.db.Exec(`update outbox set format = '' where id = ?`, id)
	return err
}

func (s *Store) recordError(id int64, sendErr error) {
	_, _ = s.db.Exec(`update outbox set last_error = ? where id = ?`, fmt.Sprint(sendErr), id)
}

func (s *Store) fail(id int64, attempts int, sendErr error) {
	_, _ = s.db.Exec(`update outbox set attempts = ?, last_error = ? where id = ?`,
		attempts, fmt.Sprint(sendErr), id)
}

// TelegramOffset returns the last-acked getUpdates offset, or 0 if none.
// Persisting this avoids re-delivering the long-poll window (up to ~60s of
// messages) after a daemon restart or crash.
func (s *Store) TelegramOffset() int64 {
	var v string
	if err := s.db.QueryRow(`select v from kv where k = 'tg_offset'`).Scan(&v); err != nil {
		return 0
	}
	n, _ := strconv.ParseInt(v, 10, 64)
	return n
}

func (s *Store) SetTelegramOffset(offset int64) error {
	_, err := s.db.Exec(
		`insert into kv(k, v) values('tg_offset', ?) on conflict(k) do update set v = excluded.v`,
		strconv.FormatInt(offset, 10),
	)
	if err != nil {
		s.persistAlerted.Do(func() {
			s.fireAlert("⚠️ outbox cannot persist tg offset: " + err.Error())
		})
	}
	return err
}

