package outbox

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode/utf8"

	_ "github.com/mattn/go-sqlite3"

	"picoman/internal/transport"
)

const (
	maxMessageBytes = 4000
	maxAttempts     = 5
	baseBackoff     = time.Second
	maxBackoff      = time.Minute
)

type Store struct {
	db      *sql.DB
	clients map[string]transport.Client
	done    chan struct{} // closed when Run exits
	enabled func(string) bool

	// alert is a direct-to-user sink for internal outbox issues that we don't
	// want to route back through the outbox itself (offset persistence
	// failures, oversize messages, etc.). Set by daemon at startup.
	alert          func(text string)
	trimAlerted    sync.Once
	persistAlerted sync.Once
}

type message struct {
	id        int64
	transport string
	chatID    string
	replyToID string
	format    string
	text      string
	attempts  int
}

type retryError struct{ delay time.Duration }

func (e *retryError) Error() string { return "delivery retry scheduled" }

func Open(path string, clients map[string]transport.Client) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite3", path)
	if err != nil {
		return nil, err
	}
	s := &Store{db: db, clients: clients, done: make(chan struct{})}
	if err := s.init(); err != nil {
		db.Close()
		return nil, err
	}
	_ = os.Chmod(path, 0o600)
	return s, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

func (s *Store) EnqueueTo(address transport.Address, replyToID, format, text string) error {
	// Messages are generated by callers with bounded fields; if a producer
	// ever exceeds the Telegram limit we trim hard and keep going rather
	// than reassemble HTML across chunks (which loses tags and is fragile).
	if len(text) > maxMessageBytes {
		log.Printf("outbox message too long (transport=%s chat=%s format=%q bytes=%d); hard-trimming", address.Transport, address.ChatID, format, len(text))
		s.trimAlerted.Do(func() {
			s.fireAlert(fmt.Sprintf("⚠️ outbox hard-trim: message %d bytes (limit %d); producer bug", len(text), maxMessageBytes))
		})
		text = trimUTF8(text, maxMessageBytes)
	}
	return s.insert(address.Transport, replyToID, address.ChatID, format, text)
}

// trimUTF8 cuts at most n bytes from s on a UTF-8 boundary.
func trimUTF8(s string, n int) string {
	if len(s) <= n {
		return s
	}
	for n > 0 && !utf8.RuneStart(s[n]) {
		n--
	}
	return s[:n]
}

func (s *Store) insert(transportName, replyToID, chatID, format, text string) error {
	switch transportName {
	case "tg":
		chat, err := strconv.ParseInt(chatID, 10, 64)
		if err != nil {
			return fmt.Errorf("bad Telegram chat id: %w", err)
		}
		var reply int64
		if replyToID != "" {
			reply, err = strconv.ParseInt(replyToID, 10, 64)
			if err != nil {
				return fmt.Errorf("bad Telegram reply id: %w", err)
			}
		}
		_, err = s.db.Exec(`
insert into outbox(chat_id, reply_to_id, format, text, created_at)
values(?, ?, ?, ?, unixepoch())
`, chat, reply, format, text)
		return err
	case "mx":
		_, err := s.db.Exec(`
insert into max_outbox(chat_id, reply_to_id, format, text, created_at)
values(?, ?, ?, ?, unixepoch())
`, chatID, replyToID, format, text)
		return err
	default:
		return fmt.Errorf("unknown transport %q", transportName)
	}
}

// Done is closed when the Run goroutine has exited. Use it to wait before
// calling Flush during shutdown so two senders don't pick the same row.
func (s *Store) Done() <-chan struct{} { return s.done }

// SetAlertSink wires a direct-to-user notification function for internal
// issues. The sink should bypass this outbox so a broken outbox can still
// alert. May be nil (alerts then drop to the journal only).
func (s *Store) SetAlertSink(fn func(text string)) { s.alert = fn }

func (s *Store) SetTransportEnabled(fn func(string) bool) { s.enabled = fn }

// fireAlert calls the alert sink if set, otherwise just logs.
func (s *Store) fireAlert(text string) {
	log.Printf("outbox alert: %s", text)
	if s.alert != nil {
		s.alert(text)
	}
}

func (s *Store) Run(ctx context.Context) {
	defer close(s.done)
	var wg sync.WaitGroup
	for name := range s.clients {
		wg.Add(1)
		go func(transportName string) {
			defer wg.Done()
			s.runTransport(ctx, transportName)
		}(name)
	}
	wg.Wait()
}

func (s *Store) runTransport(ctx context.Context, transportName string) {
	wait := baseBackoff
	for {
		if s.enabled != nil && !s.enabled(transportName) {
			if !sleepCtx(ctx, time.Second) {
				return
			}
			continue
		}
		err := s.sendOne(ctx, transportName)
		switch {
		case errors.Is(err, sql.ErrNoRows):
			wait = baseBackoff
			if !sleepCtx(ctx, time.Second) {
				return
			}
		case err == nil:
			wait = baseBackoff
		default:
			delay := wait
			var retry *retryError
			if errors.As(err, &retry) && retry.delay > 0 {
				delay = retry.delay
			}
			if !sleepCtx(ctx, delay) {
				return
			}
			if retry == nil || retry.delay == 0 {
				wait *= 2
				if wait > maxBackoff {
					wait = maxBackoff
				}
			} else {
				wait = baseBackoff
			}
		}
	}
}

func (s *Store) Flush(ctx context.Context) {
	var wg sync.WaitGroup
	for name := range s.clients {
		wg.Add(1)
		go func(transportName string) {
			defer wg.Done()
			s.flushTransport(ctx, transportName)
		}(name)
	}
	wg.Wait()
}

func (s *Store) flushTransport(ctx context.Context, transportName string) {
	wait := baseBackoff
	for ctx.Err() == nil {
		if s.enabled != nil && !s.enabled(transportName) {
			return
		}
		err := s.sendOne(ctx, transportName)
		if errors.Is(err, sql.ErrNoRows) {
			if !s.hasPending(transportName) {
				return
			}
			if !sleepCtx(ctx, time.Second) {
				return
			}
			continue
		}
		if err != nil {
			delay := wait
			var retry *retryError
			if errors.As(err, &retry) && retry.delay > 0 {
				delay = retry.delay
			}
			if !sleepCtx(ctx, delay) {
				return
			}
			if retry == nil || retry.delay == 0 {
				wait *= 2
				if wait > maxBackoff {
					wait = maxBackoff
				}
			} else {
				wait = baseBackoff
			}
		} else {
			wait = baseBackoff
		}
	}
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-t.C:
		return true
	case <-ctx.Done():
		return false
	}
}

func (s *Store) SendOne(ctx context.Context) error {
	for _, name := range []string{"tg", "mx"} {
		if s.clients[name] == nil {
			continue
		}
		err := s.sendOne(ctx, name)
		if !errors.Is(err, sql.ErrNoRows) {
			return err
		}
	}
	return sql.ErrNoRows
}

func (s *Store) sendOne(ctx context.Context, transportName string) error {
	msg, err := s.next(transportName)
	if err != nil {
		return err
	}
	sendErr := s.send(ctx, msg)
	if sendErr == nil {
		log.Printf("outbox sent id=%d transport=%s chat=%s", msg.id, msg.transport, msg.chatID)
		return s.markSent(msg)
	}

	// Reply target gone: drop reply_to and retry on next tick.
	if msg.replyToID != "" && isReplyTargetGone(sendErr) {
		log.Printf("outbox reply target gone id=%d transport=%s chat=%s: %v", msg.id, msg.transport, msg.chatID, sendErr)
		_ = s.clearReplyTo(msg)
		return &retryError{}
	}

	// HTML rejected permanently (e.g. parse_error from a malformed tag in our
	// own generator): retry once as plain so users see *something* — visible
	// raw tags beat a dead-lettered message.
	if msg.format == "html" && isPermanent(sendErr) {
		plain := msg
		plain.format = ""
		if plainErr := s.send(ctx, plain); plainErr == nil {
			log.Printf("outbox sent (html→plain fallback) id=%d transport=%s chat=%s: original %v", msg.id, msg.transport, msg.chatID, sendErr)
			_ = s.clearFormat(msg)
			return s.markSent(msg)
		} else {
			// Plain also rejected — fall through with the new error.
			sendErr = plainErr
		}
	}

	if !isPermanent(sendErr) {
		delay := baseBackoff
		log.Printf("outbox transient id=%d transport=%s chat=%s: %v", msg.id, msg.transport, msg.chatID, sendErr)
		// Honor Telegram's retry_after hint: if we keep hammering through it,
		// the API may escalate the cooldown. Cap at 5 min for safety.
		var apiErr *transport.APIError
		if errors.As(sendErr, &apiErr) && apiErr.RetryAfter > 0 {
			wait := time.Duration(apiErr.RetryAfter) * time.Second
			if wait > 5*time.Minute {
				wait = 5 * time.Minute
			}
			delay = wait
			log.Printf("outbox honoring retry_after id=%d transport=%s chat=%s wait=%s", msg.id, msg.transport, msg.chatID, wait)
		}
		s.deferMessage(msg, delay, sendErr)
		hint := time.Duration(0)
		if delay > baseBackoff {
			hint = delay
		}
		return &retryError{delay: hint}
	}

	attempts := msg.attempts + 1
	s.fail(msg, attempts, sendErr)
	if attempts >= maxAttempts {
		s.markDead(msg)
		log.Printf("outbox dead id=%d transport=%s chat=%s attempts=%d: %v", msg.id, msg.transport, msg.chatID, attempts, sendErr)
		go s.notifyDead(msg, sendErr)
		return nil
	}
	log.Printf("outbox permanent id=%d transport=%s chat=%s attempts=%d: %v", msg.id, msg.transport, msg.chatID, attempts, sendErr)
	s.deferMessage(msg, baseBackoff, sendErr)
	return &retryError{}
}

func isPermanent(err error) bool {
	var apiErr *transport.APIError
	return errors.As(err, &apiErr) && !apiErr.IsRetryable()
}

func (s *Store) send(ctx context.Context, msg message) error {
	client := s.clients[msg.transport]
	if client == nil {
		return &transport.APIError{Platform: msg.transport, Code: 400, Description: "transport unavailable"}
	}
	_, err := client.Send(ctx, msg.chatID, msg.replyToID, msg.text, msg.format)
	return err
}

func isReplyTargetGone(err error) bool {
	var apiErr *transport.APIError
	if !errors.As(err, &apiErr) {
		return false
	}
	desc := strings.ToLower(apiErr.Description)
	if strings.Contains(desc, "message to be replied") {
		return true
	}
	return strings.Contains(desc, "reply") &&
		(strings.Contains(desc, "not found") ||
			strings.Contains(desc, "invalid") ||
			strings.Contains(desc, "deleted"))
}

func (s *Store) notifyDead(msg message, sendErr error) {
	text := fmt.Sprintf("outbox dead id=%d: %s", msg.id, sendErr)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if client := s.clients[msg.transport]; client != nil {
		_, _ = client.Send(ctx, msg.chatID, "", text, "")
	}
}

func (s *Store) init() error {
	// Pragmas: WAL gives concurrent readers + one writer without "database is
	// locked" thrash; busy_timeout retries lock acquisition briefly instead of
	// failing immediately under contention.
	if _, err := s.db.Exec(`PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;`); err != nil {
		return err
	}
	_, err := s.db.Exec(`
create table if not exists outbox (
	id integer primary key autoincrement,
	chat_id integer not null,
	reply_to_id integer not null default 0,
	format text not null default '',
	text text not null,
	created_at integer not null,
	sent_at integer,
	dead_at integer,
	attempts integer not null default 0,
	last_error text not null default ''
);
create index if not exists outbox_pending on outbox(sent_at, dead_at, id);
create table if not exists max_outbox (
	id integer primary key autoincrement,
	chat_id text not null,
	reply_to_id text not null default '',
	format text not null default '',
	text text not null,
	created_at integer not null,
	sent_at integer,
	dead_at integer,
	attempts integer not null default 0,
	last_error text not null default '',
	next_attempt_at integer not null default 0
);
create index if not exists max_outbox_pending on max_outbox(sent_at, dead_at, id);
create table if not exists kv (
	k text primary key,
	v text not null
);
`)
	return err
}

func (s *Store) next(transportName string) (message, error) {
	var msg message
	msg.transport = transportName
	switch transportName {
	case "tg":
		var chatID, replyToID int64
		err := s.db.QueryRow(`
select id, chat_id, reply_to_id, format, text, attempts
from outbox
where sent_at is null and dead_at is null
order by id
limit 1
`).Scan(&msg.id, &chatID, &replyToID, &msg.format, &msg.text, &msg.attempts)
		msg.chatID = strconv.FormatInt(chatID, 10)
		if replyToID != 0 {
			msg.replyToID = strconv.FormatInt(replyToID, 10)
		}
		return msg, err
	case "mx":
		err := s.db.QueryRow(`
select id, chat_id, reply_to_id, format, text, attempts
from max_outbox
where id = (
	select id from max_outbox
	where sent_at is null and dead_at is null
	order by id
	limit 1
) and next_attempt_at <= unixepoch()
`).Scan(&msg.id, &msg.chatID, &msg.replyToID, &msg.format, &msg.text, &msg.attempts)
		return msg, err
	default:
		return msg, sql.ErrNoRows
	}
}

func (s *Store) hasPending(transportName string) bool {
	table := tableFor(transportName)
	if table == "" {
		return false
	}
	var one int
	return s.db.QueryRow(`select 1 from `+table+` where sent_at is null and dead_at is null limit 1`).Scan(&one) == nil
}

func tableFor(transportName string) string {
	switch transportName {
	case "tg":
		return "outbox"
	case "mx":
		return "max_outbox"
	default:
		return ""
	}
}

func (s *Store) markSent(msg message) error {
	_, err := s.db.Exec(`update `+tableFor(msg.transport)+` set sent_at = unixepoch() where id = ?`, msg.id)
	return err
}

func (s *Store) markDead(msg message) {
	_, _ = s.db.Exec(`update `+tableFor(msg.transport)+` set dead_at = unixepoch() where id = ?`, msg.id)
}

func (s *Store) clearReplyTo(msg message) error {
	value := any("")
	if msg.transport == "tg" {
		value = int64(0)
	}
	_, err := s.db.Exec(`update `+tableFor(msg.transport)+` set reply_to_id = ? where id = ?`, value, msg.id)
	return err
}

func (s *Store) clearFormat(msg message) error {
	_, err := s.db.Exec(`update `+tableFor(msg.transport)+` set format = '' where id = ?`, msg.id)
	return err
}

func (s *Store) deferMessage(msg message, delay time.Duration, sendErr error) {
	if msg.transport == "tg" {
		_, _ = s.db.Exec(`update outbox set last_error = ? where id = ?`, fmt.Sprint(sendErr), msg.id)
		return
	}
	seconds := int64(delay / time.Second)
	if seconds < 1 {
		seconds = 1
	}
	_, _ = s.db.Exec(`update max_outbox set next_attempt_at = unixepoch() + ?, last_error = ? where id = ?`,
		seconds, fmt.Sprint(sendErr), msg.id)
}

func (s *Store) fail(msg message, attempts int, sendErr error) {
	_, _ = s.db.Exec(`update `+tableFor(msg.transport)+` set attempts = ?, last_error = ? where id = ?`,
		attempts, fmt.Sprint(sendErr), msg.id)
}

// TelegramOffset returns the last-acked getUpdates offset, or 0 if none.
// Persisting this avoids re-delivering the long-poll window (up to ~60s of
// messages) after a daemon restart or crash.
func (s *Store) TelegramOffset() int64 {
	var v string
	if err := s.db.QueryRow(`select v from kv where k = 'tg_offset'`).Scan(&v); err != nil {
		return 0
	}
	n, _ := strconv.ParseInt(v, 10, 64)
	return n
}

func (s *Store) SetTelegramOffset(offset int64) error {
	_, err := s.db.Exec(
		`insert into kv(k, v) values('tg_offset', ?) on conflict(k) do update set v = excluded.v`,
		strconv.FormatInt(offset, 10),
	)
	if err != nil {
		s.persistAlerted.Do(func() {
			s.fireAlert("⚠️ outbox cannot persist tg offset: " + err.Error())
		})
	}
	return err
}
