package outbox

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"
	"unicode/utf8"

	_ "github.com/mattn/go-sqlite3"

	"picoman/internal/tg"
)

const (
	maxMessageBytes = 4000
	maxAttempts     = 5
	baseBackoff     = time.Second
	maxBackoff      = time.Minute
)

type Store struct {
	db  *sql.DB
	bot *tg.Client
}

type message struct {
	id        int64
	chatID    int64
	replyToID int64
	format    string
	text      string
	attempts  int
}

func Open(path string, bot *tg.Client) (*Store, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return nil, err
	}
	db, err := sql.Open("sqlite3", path)
	if err != nil {
		return nil, err
	}
	s := &Store{db: db, bot: bot}
	if err := s.init(); err != nil {
		db.Close()
		return nil, err
	}
	_ = os.Chmod(path, 0o600)
	return s, nil
}

func (s *Store) Close() error {
	return s.db.Close()
}

func (s *Store) Enqueue(chatID int64, text string) error {
	return s.enqueue(chatID, 0, "", text)
}

func (s *Store) EnqueueReply(chatID, replyToID int64, text string) error {
	return s.enqueue(chatID, replyToID, "", text)
}

func (s *Store) EnqueueHTML(chatID int64, text string) error {
	return s.enqueue(chatID, 0, "html", text)
}

func (s *Store) EnqueueHTMLReply(chatID, replyToID int64, text string) error {
	return s.enqueue(chatID, replyToID, "html", text)
}

func (s *Store) enqueue(chatID, replyToID int64, format, text string) error {
	// Messages are generated by callers with bounded fields; if a producer
	// ever exceeds the Telegram limit we trim hard and keep going rather
	// than reassemble HTML across chunks (which loses tags and is fragile).
	if len(text) > maxMessageBytes {
		log.Printf("outbox message too long (chat=%d format=%q bytes=%d); hard-trimming", chatID, format, len(text))
		text = trimUTF8(text, maxMessageBytes)
	}
	return s.insert(replyToID, chatID, format, text)
}

// trimUTF8 cuts at most n bytes from s on a UTF-8 boundary.
func trimUTF8(s string, n int) string {
	if len(s) <= n {
		return s
	}
	for n > 0 && !utf8.RuneStart(s[n]) {
		n--
	}
	return s[:n]
}

func (s *Store) insert(replyToID, chatID int64, format, text string) error {
	_, err := s.db.Exec(`
insert into outbox(chat_id, reply_to_id, format, text, created_at)
values(?, ?, ?, ?, unixepoch())
`, chatID, replyToID, format, text)
	return err
}

func (s *Store) Run(ctx context.Context) {
	wait := baseBackoff
	for {
		err := s.SendOne(ctx)
		switch {
		case errors.Is(err, sql.ErrNoRows):
			wait = baseBackoff
			if !sleepCtx(ctx, time.Second) {
				return
			}
		case err == nil:
			wait = baseBackoff
		default:
			if !sleepCtx(ctx, wait) {
				return
			}
			wait *= 2
			if wait > maxBackoff {
				wait = maxBackoff
			}
		}
	}
}

func (s *Store) Flush(ctx context.Context) {
	for ctx.Err() == nil {
		err := s.SendOne(ctx)
		if errors.Is(err, sql.ErrNoRows) {
			return
		}
		if err != nil && !sleepCtx(ctx, time.Second) {
			return
		}
	}
}

func sleepCtx(ctx context.Context, d time.Duration) bool {
	t := time.NewTimer(d)
	defer t.Stop()
	select {
	case <-t.C:
		return true
	case <-ctx.Done():
		return false
	}
}

func (s *Store) SendOne(ctx context.Context) error {
	msg, err := s.next()
	if err != nil {
		return err
	}
	sendErr := s.send(ctx, msg)
	if sendErr == nil {
		log.Printf("outbox sent id=%d chat=%d", msg.id, msg.chatID)
		return s.markSent(msg.id)
	}

	// Reply target gone: drop reply_to and retry on next tick.
	if msg.replyToID > 0 && isReplyTargetGone(sendErr) {
		log.Printf("outbox reply target gone id=%d chat=%d: %v", msg.id, msg.chatID, sendErr)
		_ = s.clearReplyTo(msg.id)
		return sendErr
	}

	// HTML rejected permanently (e.g. parse_error from a malformed tag in our
	// own generator): retry once as plain so users see *something* — visible
	// raw tags beat a dead-lettered message.
	if msg.format == "html" && isPermanent(sendErr) {
		plain := msg
		plain.format = ""
		if plainErr := s.send(ctx, plain); plainErr == nil {
			log.Printf("outbox sent (html→plain fallback) id=%d chat=%d: original %v", msg.id, msg.chatID, sendErr)
			_ = s.clearFormat(msg.id)
			return s.markSent(msg.id)
		} else {
			// Plain also rejected — fall through with the new error.
			sendErr = plainErr
		}
	}

	if !isPermanent(sendErr) {
		s.recordError(msg.id, sendErr)
		log.Printf("outbox transient id=%d chat=%d: %v", msg.id, msg.chatID, sendErr)
		return sendErr
	}

	attempts := msg.attempts + 1
	s.fail(msg.id, attempts, sendErr)
	if attempts >= maxAttempts {
		s.markDead(msg.id)
		log.Printf("outbox dead id=%d chat=%d attempts=%d: %v", msg.id, msg.chatID, attempts, sendErr)
		go s.notifyDead(msg, sendErr)
		return nil
	}
	log.Printf("outbox permanent id=%d chat=%d attempts=%d: %v", msg.id, msg.chatID, attempts, sendErr)
	return sendErr
}

func isPermanent(err error) bool {
	var apiErr *tg.APIError
	return errors.As(err, &apiErr) && !apiErr.IsRetryable()
}

func (s *Store) send(ctx context.Context, msg message) error {
	switch {
	case msg.format == "html" && msg.replyToID > 0:
		return s.bot.SendHTMLReply(ctx, msg.chatID, msg.replyToID, msg.text)
	case msg.format == "html":
		return s.bot.SendHTML(ctx, msg.chatID, msg.text)
	case msg.replyToID > 0:
		return s.bot.SendReply(ctx, msg.chatID, msg.replyToID, msg.text)
	default:
		return s.bot.SendMessage(ctx, msg.chatID, msg.text)
	}
}

func isReplyTargetGone(err error) bool {
	var apiErr *tg.APIError
	if !errors.As(err, &apiErr) {
		return false
	}
	desc := strings.ToLower(apiErr.Description)
	if strings.Contains(desc, "message to be replied") {
		return true
	}
	return strings.Contains(desc, "reply") &&
		(strings.Contains(desc, "not found") ||
			strings.Contains(desc, "invalid") ||
			strings.Contains(desc, "deleted"))
}

func (s *Store) notifyDead(msg message, sendErr error) {
	text := fmt.Sprintf("outbox dead id=%d: %s", msg.id, sendErr)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_ = s.bot.SendMessage(ctx, msg.chatID, text)
}

func (s *Store) init() error {
	_, err := s.db.Exec(`
create table if not exists outbox (
	id integer primary key autoincrement,
	chat_id integer not null,
	reply_to_id integer not null default 0,
	format text not null default '',
	text text not null,
	created_at integer not null,
	sent_at integer,
	dead_at integer,
	attempts integer not null default 0,
	last_error text not null default ''
);
create index if not exists outbox_pending on outbox(sent_at, dead_at, id);
`)
	if err != nil {
		return err
	}
	_, _ = s.db.Exec(`alter table outbox add column reply_to_id integer not null default 0`)
	_, _ = s.db.Exec(`alter table outbox add column format text not null default ''`)
	_, _ = s.db.Exec(`alter table outbox add column dead_at integer`)
	return err
}

func (s *Store) next() (message, error) {
	var msg message
	err := s.db.QueryRow(`
select id, chat_id, reply_to_id, format, text, attempts
from outbox
where sent_at is null and dead_at is null
order by id
limit 1
`).Scan(&msg.id, &msg.chatID, &msg.replyToID, &msg.format, &msg.text, &msg.attempts)
	return msg, err
}

func (s *Store) markSent(id int64) error {
	_, err := s.db.Exec(`update outbox set sent_at = unixepoch() where id = ?`, id)
	return err
}

func (s *Store) markDead(id int64) {
	_, _ = s.db.Exec(`update outbox set dead_at = unixepoch() where id = ?`, id)
}

func (s *Store) clearReplyTo(id int64) error {
	_, err := s.db.Exec(`update outbox set reply_to_id = 0 where id = ?`, id)
	return err
}

func (s *Store) clearFormat(id int64) error {
	_, err := s.db.Exec(`update outbox set format = '' where id = ?`, id)
	return err
}

func (s *Store) recordError(id int64, sendErr error) {
	_, _ = s.db.Exec(`update outbox set last_error = ? where id = ?`, fmt.Sprint(sendErr), id)
}

func (s *Store) fail(id int64, attempts int, sendErr error) {
	_, _ = s.db.Exec(`update outbox set attempts = ?, last_error = ? where id = ?`,
		attempts, fmt.Sprint(sendErr), id)
}

