name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        env:
          CGO_ENABLED: "1"
          GOOS: linux
          GOARCH: amd64
        run: |
          go build -trimpath -ldflags="-s -w" -o picoman-linux-amd64 ./cmd/picoman
          sha256sum picoman-linux-amd64 > picoman-linux-amd64.sha256
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            picoman-linux-amd64
            picoman-linux-amd64.sha256
